server:
  port: 8080

spring:
  application:
    name: minio-service
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

# MinIO Configuration
minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: documents
  secure: false

# Logging Configuration
logging:
  level:
    com.example: DEBUG
    io.minio: DEBUG
